# Generated by Django 2.2.7 on 2019-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edStaff',
            fields=[
                ('staff_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stf_fname', models.CharField(max_length=30)),
                ('stf_lname', models.CharField(max_length=30)),
                ('stf_userid', models.CharField(max_length=10)),
                ('stf_idnumber', models.CharField(max_length=30)),
                ('stf_dob', models.DateField()),
                ('stf_phone', models.CharField(max_length=30)),
                ('stf_email', models.CharField(max_length=30)),
                ('stf_dept_id', models.CharField(max_length=30)),
                ('stf_addr1', models.CharField(max_length=30)),
                ('stf_addr2', models.CharField(max_length=30)),
                ('std_other1', models.CharField(max_length=30)),
                ('std_other2', models.CharField(max_length=30)),
            ],
        ),
    ]
